### ISSUE TITLE
`npm create waku@latest` fails

### ISSUE THREAD

**Issue by infomiho** [dai-shi/waku#128]
For me creating a new example app fails with the following:

```
Error: ENOENT: no such file or directory, scandir 'template'
    at Object.readdirSync (node:fs:1452:3)
    at init (/Users/ilakovac/Library/pnpm/store/v3/tmp/dlx-17047/node_modules/.pnpm/create-waku@0.5.1/node_modules/create-waku/dist/cli.js:7633:42)
    at Object.<anonymous> (/Users/ilakovac/Library/pnpm/store/v3/tmp/dlx-17047/node_modules/.pnpm/create-waku@0.5.1/node_modules/create-waku/dist/cli.js:7742:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'template'
}
```

Same thing happens with:
- `pnpm create waku`
- `yarn create waku`

I supposed this is the line at fault: https://github.com/dai-shi/waku/blob/main/packages/create-waku/src/cli.ts#L38

**Comment by infomiho** [comment]
This is probably fixed by: https://github.com/dai-shi/waku/pull/127

**Comment by dai-shi** [comment]
Yeah, thanks for reporting! We are working on it.

**Comment by infomiho** [comment]
Latest fixes this for me 👍

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/create-waku/v/0.5.2 is published thanks to @vasucp1207
