### ISSUE TITLE
Can't run a Waku 0.17.0 application on Windows 11 with Node v18.14.0

### ISSUE THREAD

**Issue by mauricedb** [dai-shi/waku#173]
Step taken:

- npm create waku@latest
- Template: async-template

Setting up project was fine
```
PS C:\Temp> npm create waku@latest
√ Project Name ... waku-project
√ Choose a starter template » async-template
Setting up project...

Done. Now run:

cd waku-project
npm install
npm run dev
```

Next cd into project and try to start the development server with `npm run dev`

Resulting console output when opening http://localhost:3000/ in the browser:
```
(node:14372) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14372) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getSource, transformSource
Error: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1159:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:429:21)
    at importModuleDynamically (node:internal/vm:102:46)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at preloadModule (C:\temp\waku-project\node_modules\react-server-dom-webpack\cjs\react-server-dom-webpack-client.node.unbundled.development.js:98:41)
    at resolveModule (C:\temp\waku-project\node_modules\react-server-dom-webpack\cjs\react-server-dom-webpack-client.node.unbundled.development.js:1915:17)
    at processFullRow (C:\temp\waku-project\node_modules\react-server-dom-webpack\cjs\react-server-dom-webpack-client.node.unbundled.development.js:1986:9)
    at processBinaryChunk (C:\temp\waku-project\node_modules\react-server-dom-webpack\cjs\react-server-dom-webpack-client.node.unbundled.development.js:2134:7)
    at PassThrough.<anonymous> (C:\temp\waku-project\node_modules\react-server-dom-webpack\cjs\react-server-dom-webpack-client.node.unbundled.development.js:2207:5)
    at PassThrough.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at node:internal/streams/transform:182:12
    at PassThrough._transform (node:internal/streams/passthrough:46:3)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at PassThrough.<anonymous> (file:///C:/temp/waku-project/node_modules/waku/dist/lib/middleware/rsc/ssr.js:370:16)
    at PassThrough.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at node:internal/streams/transform:182:12
    at PassThrough._transform (node:internal/streams/passthrough:46:3)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at file:///C:/temp/waku-project/node_modules/waku/dist/lib/middleware/rsc/worker-api.js:420:29
    at Worker.<anonymous> (file:///C:/temp/waku-project/node_modules/waku/dist/lib/middleware/rsc/worker-api.js:245:121)
    at Worker.emit (node:events:525:35)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at MessagePort.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
Error: The destination stream errored while writing data.
    at Transform.<anonymous> (C:\temp\waku-project\node_modules\react-dom\cjs\react-dom-server.node.development.js:11660:20)
    at Transform.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Environment:
```
PS C:\Temp\waku-project> node -v
v18.14.0
```

**Comment by himself65** [comment]
I would like to help on this

**Comment by himself65** [comment]
related: https://github.com/nodejs/node/issues/31710

**Comment by himself65** [comment]
@dai-shi this should be closed
