### ISSUE TITLE
npm create waku@latest seems broken

### ISSUE THREAD

**Issue by dosco** [dai-shi/waku#188]
I'm running Node.js v21.1.0 when I access the site in the browser after creating it I get the below stack trace and nothing is rendered.

```                                                              
❯ cd ..
❯ rm -rf app
❯ npm create waku@latest

✔ Project Name … app
✔ Choose a starter template › async-template
Setting up project...

Done. Now run:

cd app
npm install
npm run dev

❯ cd app
❯ npm i
❯ npm run dev

> app@0.0.0 dev
> waku dev --with-ssr

ready: Listening on http://localhost:3000/
You did not run Node.js with the `--conditions react-server` flag. Any "react-server" override will only work with ESM imports.
Error: Missing Root component
    at Slot (file:///test/app/node_modules/waku/dist/client.js:88:15)
    at renderWithHooks (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:9508:16)
    at renderIndeterminateComponent (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:9585:15)
    at renderElement (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:9853:7)
    at renderNodeDestructiveImpl (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:10152:13)
    at renderNodeDestructive (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:10106:14)
    at renderContextProvider (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:9813:3)
    at renderElement (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:9936:11)
    at renderNodeDestructiveImpl (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:10152:13)
    at renderNodeDestructive (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:10106:14)
    at finishFunctionComponent (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:9679:5)
    at renderIndeterminateComponent (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:9625:5)
    at renderElement (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:9853:7)
    at renderNodeDestructiveImpl (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:10152:13)
    at renderNodeDestructive (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:10106:14)
    at retryRenderTask (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:10980:5)
    at retryTask (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:10947:5)
    at performWork (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:11137:7)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Immediate._onImmediate (/test/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:11537:29)
    at process.processImmediate (node:internal/timers:478:21)
```

**Comment by dai-shi** [comment]
Oh, no. What happened.
Yeah, confirmed the issue. Thanks for reporting.

**Comment by dai-shi** [comment]
This looks tough. I'll keep investigating.

Please do either of the followings in the meantime:
- Remove `--with-ssr` in "dev" script in package.json (It works for "build" and "start")
- Use `npm create waku@0.6.2` which is the previous version

**Comment by dai-shi** [comment]
The issue is also reproduced in the repo.
We will work on it for the next release.

> Remove `--with-ssr` in "dev" script in package.json

Meanwhile, I will publish a patch for that.

**Comment by dai-shi** [comment]
`create-waku@0.6.5` should be it. It shouldn't cause the error in the OP now.
