### ISSUE TITLE
url with `?a=b` will crash vercel serverless function

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#253]
```shell
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: not handled","reason":{"errorType":"Error","errorMessage":"not handled","stack":["Error: not handled","    at file:///var/task/serve.js:7:11","    at file:///var/task/node_modules/waku/dist/lib/rsc/handler-prd.js:93:9","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: not handled","    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    at process.emit (node:events:529:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```

**Comment by himself65** [comment]
workaround:
![image](https://github.com/dai-shi/waku/assets/14026360/f826a431-0953-44e5-999a-4fd812611657)

**Comment by dai-shi** [comment]
So, I wanted to support RSC static sites with query params, but that was the wrong decision. We should just ignore query params for static sites regardless of with or without SSR(SSG).

**Comment by dai-shi** [comment]
#256 fixed the "crash", so the issue was fixed at that point. Reopening this because we need to avoid 404 too.
