### ISSUE TITLE
vite warning with examples/12_css

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#277]
If we run ` npm run examples:prd:12_css`, it shows:

```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```

Same happens with ` npm run examples:dev:12_css`

@Aslemammad Can you investigate it?

**Comment by Aslemammad** [comment]
I'll do, can you assign this one to me?

**Comment by himself65** [comment]
```
/Users/himself65/Library/Caches/fnm_multishells/2120_1702514758322/bin/pnpm run dev

> waku-example@0.1.0 dev /Users/himself65/Code/waku/examples/12_css
> VITE_CJS_TRACE=true waku dev --with-ssr

ready: Listening on http://localhost:3000/
Trace: The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
    at warnCjsUsage (/Users/himself65/Code/waku/node_modules/.pnpm/vite@5.0.9_@types+node@20.10.4/node_modules/vite/index.cjs:32:3)
    at Object.<anonymous> (/Users/himself65/Code/waku/node_modules/.pnpm/vite@5.0.9_@types+node@20.10.4/node_modules/vite/index.cjs:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+vite-plugin@3.9.3_@types+node@20.10.4_vite@5.0.9/node_modules/@vanilla-extract/vite-plugin/dist/vanilla-extract-vite-plugin.cjs.dev.js:6:12)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
Trace: The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
    at warnCjsUsage (/Users/himself65/Code/waku/node_modules/.pnpm/vite@5.0.9_@types+node@20.10.4/node_modules/vite/index.cjs:32:3)
    at Object.<anonymous> (/Users/himself65/Code/waku/node_modules/.pnpm/vite@5.0.9_@types+node@20.10.4/node_modules/vite/index.cjs:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+vite-plugin@3.9.3_@types+node@20.10.4_vite@5.0.9/node_modules/@vanilla-extract/vite-plugin/dist/vanilla-extract-vite-plugin.cjs.dev.js:6:12)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

**Comment by himself65** [comment]
https://github.com/vanilla-extract-css/vanilla-extract/issues/1236

**Comment by Aslemammad** [comment]
So we cannot do anything on our side, correct?

**Comment by himself65** [comment]
Yep

**Comment by dai-shi** [comment]
okay, i'll close this as it will be fixed when upstream does.
