### ISSUE TITLE
Error: Unexpected client entry in PRD (when building outside the repo)

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#320]
```shell
/Users/himself65/Library/Caches/fnm_multishells/1950_1703280064036/bin/pnpm run build

> himself65-intro@0.1.0 build /Users/himself65/Code/intro
> waku build --with-ssr

vite v5.0.10 building SSR bundle for production...
✓ 37 modules transformed.
✓ built in 269ms
vite v5.0.10 building SSR bundle for production...
✓ 35 modules transformed.
dist/assets/rsc0-c6f3ad6ee.js         0.23 kB
dist/assets/layout-JpyLhZun.js        0.97 kB
dist/assets/jsx-runtime-avYYPWRQ.js   1.11 kB
dist/assets/page-M2w3R4qw.js          1.73 kB
dist/assets/page--UHqYV3w.js          2.84 kB
dist/assets/waku-client.js            3.36 kB
dist/entries.js                       4.96 kB
dist/assets/com0-6e0253e59.js        10.82 kB
dist/rsdw-server.js                  40.72 kB
✓ built in 94ms
vite v5.0.10 building for production...
✓ 63 modules transformed.
dist/public/assets/favicon-6B5X7Foh.ico            3.94 kB
dist/public/index.html                            16.76 kB │ gzip:  4.70 kB
dist/public/assets/react.js                        0.10 kB │ gzip:  0.11 kB
dist/public/assets/_commonjsHelpers-HFhYSYcO.js    0.12 kB │ gzip:  0.13 kB
dist/public/assets/rsc0-c6f3ad6ee.js               0.29 kB │ gzip:  0.20 kB
dist/public/assets/main-a7_PehH1.js                6.78 kB │ gzip:  2.92 kB
dist/public/assets/com0-6e0253e59.js               7.06 kB │ gzip:  2.99 kB
dist/public/assets/index-HPrtD3iK.js               7.45 kB │ gzip:  2.91 kB
dist/public/assets/waku-client.js                 12.75 kB │ gzip:  4.87 kB
dist/public/assets/rsdw-client.js                 13.25 kB │ gzip:  4.94 kB
dist/public/assets/rd-server.js                  155.90 kB │ gzip: 46.80 kB
dist/public/assets/index-Pfaw-c4i.js             176.90 kB │ gzip: 55.14 kB
✓ built in 559ms
id page
id layout
id page
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
id articles/hello-world/page
id layout
id articles/layout
id articles/hello-world/layout
id articles/hello-world/page
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
[Error: ENOENT: no such file or directory, open '/Users/himself65/Code/intro/dist/assets/README.mdx'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/himself65/Code/intro/dist/assets/README.mdx'
}
id page
id layout
id page
id articles/hello-world/page
id layout
id articles/layout
id articles/hello-world/layout
id articles/hello-world/page
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
[Error: ENOENT: no such file or directory, open '/Users/himself65/Code/intro/dist/assets/README.mdx'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/himself65/Code/intro/dist/assets/README.mdx'
}
id page
id articles/hello-world/page
id page
id articles/hello-world/page
id layout
id page
id layout
id articles/layout
id articles/hello-world/layout
id articles/hello-world/page
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
Error: Unexpected client entry in PRD
    at resolveClientEntry (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:13:15)
    at Object.get (file:///Users/himself65/Code/intro/node_modules/.pnpm/waku@0.18.1_@hono+node-server@1.3.3_@swc+core@1.3.101_@vitejs+plugin-react@4.2.1_hono@3.11.10_a363gdf76ou74oigofbxqsxk2a/node_modules/waku/dist/lib/rsc/rsc-renderer.js:36:24)
    at ob (file:///Users/himself65/Code/intro/dist/rsdw-server.js:653:14)
    at gb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:785:14)
    at Array.toJSON (file:///Users/himself65/Code/intro/dist/rsdw-server.js:515:14)
    at stringify (<anonymous>)
    at pb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:845:15)
    at mb (file:///Users/himself65/Code/intro/dist/rsdw-server.js:863:7)
    at Timeout._onTimeout (file:///Users/himself65/Code/intro/dist/rsdw-server.js:900:12)
    at listOnTimeout (node:internal/timers:573:17)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: ''
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: ''
}

Node.js v20.10.0
 ELIFECYCLE  Command failed with exit code 1.

Process finished with exit code 1

```

**Comment by himself65** [comment]
https://github.com/himself65/intro/pull/11

**Comment by himself65** [comment]
<img width="1499" alt="image" src="https://github.com/dai-shi/waku/assets/14026360/db3e33c7-7da5-440b-9f02-cd360f37b8e8">

**Comment by himself65** [comment]
Seems like vite bundle chunk split?

**Comment by dai-shi** [comment]
Sorry for the confusion. This `@id` is waku's thing.

It's because you externalized `next-mdx-remote` for bundling. See packages/website/vite.config.ts which does it only for dev.

**Comment by himself65** [comment]
ok, i will try later. 
Why this happens, and Im confused I have to configure all of packages whether ssr or not. This is costly

**Comment by himself65** [comment]
I tried, this has no relationship with `next-mdx-remote`, looks like some inconsistent path between prod

**Comment by dai-shi** [comment]
Hm, okay, is the problem about reading file? (`Unexpected client entry in PRD` should definitely be the issue with bundling and `external`.)

**Comment by dai-shi** [comment]
As we also bundle server side code, the path changes.
If you rely on the source code dir structure, you may need something like:
https://github.com/dai-shi/waku/blob/b4a4f0654be3e5f402b07889339270d358b86188/examples/10_dynamicroute/vite.config.ts#L19-L20

**Comment by himself65** [comment]
07_router is not working outside of waku monorepo, you can copy to a standalone git and have a try. You will see the same issue

**Comment by dai-shi** [comment]
Okay, this is a bug deep in the file path handling with vite. I'll take a further look later.

**Comment by himself65** [comment]
I've add the test case

https://github.com/dai-shi/waku/pull/322
