### ISSUE TITLE
create waku@next error on windows

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#371]
```shell
PS C:\Users\himse> pnpm create waku@next
.../Local/pnpm/store/v3/tmp/dlx-16864    |   +1 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\himse\AppData\Local\pnpm\store\v3
  Virtual store is at:             AppData/Local/pnpm/store/v3/tmp/dlx-16864/node_modules/.pnpm
.../Local/pnpm/store/v3/tmp/d.../Local/pnpm/store/v3/tmp/dlx-16864    | Progress: resolved 1, reused 0, downloaded 1, added 1, doneame » waku-project
√ Project Name ... waku-project
√ Choose a starter template » basic-template
Setting up project...

Done. Now run:

cd waku-project
pnpm install
pnpm dev

PS C:\Users\himse> cd .\waku-project\
PS C:\Users\himse\waku-project> pnpm install
Packages: +155
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\himse\AppData\Local\pnpm\store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 199, reused 143, downloaded 12, added 155, done
node_modules/.pnpm/@swc+core@1.3.102/node_modules/@swc/core: Running postinstall script, done in 69ms

dependencies:
+ react 18.3.0-canary-c5b937576-20231219
+ react-dom 18.3.0-canary-c5b937576-20231219
+ waku 0.19.0-beta.0

devDependencies:
+ @types/react 18.2.46 (18.2.47 is available)
+ @types/react-dom 18.2.18
+ typescript 5.3.3

Done in 5.4s
PS C:\Users\himse\waku-project> pnpm dev

> waku-project@0.0.0 dev C:\Users\himse\waku-project
> waku dev --with-ssr

ready: Listening on http://localhost:3000/
Failed to resolve dependency: react-server-dom-webpack/client, present in 'optimizeDeps.include'
Failed to resolve dependency: react-server-dom-webpack/client, present in 'optimizeDeps.include'
4:16:25 PM [vite] Error when evaluating SSR module /src/components/Counter.tsx: failed to import "react-server-dom-webpack/server"
|- Error: Cannot find module 'react-server-dom-webpack/server' imported from 'C:/Users/himse/waku-project/src/components/Counter.tsx'
    at nodeImport (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50537:25)
    at ssrImport (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50444:30)
    at eval (C:/Users/himse/waku-project/src/components/Counter.tsx:3:50)
    at instantiateModule (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:15)

4:16:25 PM [vite] Error when evaluating SSR module /src/components/App.tsx: failed to import "/src/components/Counter.tsx"
|- Error: Cannot find module 'react-server-dom-webpack/server' imported from 'C:/Users/himse/waku-project/src/components/Counter.tsx'
    at nodeImport (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50537:25)
    at ssrImport (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50444:30)
    at eval (C:/Users/himse/waku-project/src/components/Counter.tsx:3:50)
    at instantiateModule (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:15)

Error: Cannot find module 'react-server-dom-webpack/server' imported from 'C:/Users/himse/waku-project/src/components/Counter.tsx'
    at nodeImport (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50537:25)
    at ssrImport (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50444:30)
    at eval (C:/Users/himse/waku-project/src/components/Counter.tsx:3:50)
    at instantiateModule (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:15) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Error: Cannot find module 'react-server-dom-webpack/server' imported from 'C:/Users/himse/waku-project/src/components/Counter.tsx'
    at nodeImport (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50537:25)
    at ssrImport (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50444:30)
    at eval (C:/Users/himse/waku-project/src/components/Counter.tsx:3:50)
    at instantiateModule (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:15) {
  digest: ''
}
Cannot render RSC Error: Cannot find module 'react-server-dom-webpack/server' imported from 'C:/Users/himse/waku-project/src/components/Counter.tsx'
    at nodeImport (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50537:25)
    at ssrImport (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50444:30)
    at eval (C:/Users/himse/waku-project/src/components/Counter.tsx:3:50)
    at instantiateModule (file:///C:/Users/himse/waku-project/node_modules/.pnpm/vite@5.0.10/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:15) {
  digest: ''
}
```

**Comment by himself65** [comment]
Looks like this is not a good fix, we just skip the error.

https://github.com/dai-shi/waku/pull/355#pullrequestreview-1806716738

**Comment by himself65** [comment]
<img width="419" alt="image" src="https://github.com/dai-shi/waku/assets/14026360/7065749c-539f-42bb-a3c4-629c608cf59a">

there is no packages installed, I might doubt this is pnpm issue

**Comment by dai-shi** [comment]
It seem not only windows issue. It can happen on macos.
I'll move RSDW back to a peer dep.
