### ISSUE TITLE
path changes between `dev` and `build`

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#58]
```tsx
import { Counter } from "./Counter.js";
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'url'

const __dirname = fileURLToPath(new URL('.', import.meta.url));

const App = ({ name = "Anonymous" }) => {
  const text = readFileSync(resolve(__dirname, './input.txt'), {
    encoding: 'utf-8'
  })
  return (
    <div style={{ border: "3px red dashed", margin: "1em", padding: "1em" }}>
      <h1>Hello {name}!!</h1>
      {text}
      <h3>This is a server component.</h3>
      <Counter />
    </div>
  );
};

export default App;
```

![image](https://github.com/dai-shi/waku/assets/14026360/60ead7e2-0c86-4bdf-95cf-b225e812d674)

```shell
➜  affine-waku git:(main) ✗ yarn dev  
yarn run v1.22.19
$ waku dev
Listening on 3000
^C
➜  affine-waku git:(main) ✗ yarn build
yarn run v1.22.19
$ waku build
vite v4.3.9 building SSR bundle for production...
transforming (1) entries.tsError when using sourcemap for reporting an error: Can't resolve original location of error.
Module level directives cause errors when bundled, "use client" in "src/Counter.tsx" was ignored.
✓ 4 modules transformed.
✓ built in 56ms
vite v4.3.9 building SSR bundle for production...
transforming (1) entries.tsError when using sourcemap for reporting an error: Can't resolve original location of error.
Module level directives cause errors when bundled, "use client" in "src/Counter.tsx" was ignored.
✓ 3 modules transformed.
dist/entries.js              0.40 kB
dist/assets/rsc0.js          1.17 kB
dist/assets/App-cde87dad.js  1.37 kB
✓ built in 25ms
vite v4.3.9 building for production...
transforming (1) src/Counter.tsxError when using sourcemap for reporting an error: Can't resolve original location of error.
✓ 37 modules transformed.
dist/public/index.html                            1.09 kB │ gzip:   0.54 kB
dist/public/assets/rsc0-102901cd.js               0.82 kB │ gzip:   0.38 kB
dist/public/assets/jsx-dev-runtime-06c801c5.js   42.46 kB │ gzip:  13.51 kB
dist/public/assets/main-9c2c75fb.js             359.06 kB │ gzip: 108.57 kB
✓ built in 760ms
clientEntries { 'assets/rsc0.js': 'assets/rsc0-102901cd.js' }
Error: ENOENT: no such file or directory, open '/Users/himself65/Code/affine-waku/dist/assets/input.txt'
    at Object.openSync (node:fs:601:3)
    at Proxy.readFileSync (node:fs:469:35)
    at App (/Users/himself65/Code/affine-waku/dist/assets/App-cde87dad.js:17:38)
    at attemptResolveElement (/Users/himself65/Code/affine-waku/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-server.node.unbundled.development.js:1462:18)
    at retryTask (/Users/himself65/Code/affine-waku/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-server.node.unbundled.development.js:2063:15)
    at performWork (/Users/himself65/Code/affine-waku/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-server.node.unbundled.development.js:2125:7)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Immediate._onImmediate (/Users/himself65/Code/affine-waku/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-server.node.unbundled.development.js:2245:29)
    at process.processImmediate (node:internal/timers:476:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/himself65/Code/affine-waku/dist/assets/input.txt'
}
4:51:37 PM [vite] page reload dist/public/index.html
4:51:37 PM [vite] page reload dist/entries.js
✨  Done in 1.24s.
```

**Comment by dai-shi** [comment]
So, readFileSync isn't detected by Vite.
There would be some approaches. What would you like?
It might be better to have dev and build paths to be the same level from the root.

**Comment by Himself65** [comment]
How about
```ts
import { rootDir } from 'waku/config'
// ...
const text = readFileSync(resolve(rootDir, './src/input.txt'), {
  encoding: 'utf-8'
})
```

**Comment by dai-shi** [comment]
Actually, you can probably do this now.
```js
import { resolveConfig } from 'vite';

const { root } = resolveConfig({}, 'serve');
```

However, this wouldn't work with `vite.prd.config.ts` which has a different root.

**Comment by himself65** [comment]
I faced the same problem here

https://github.com/toeverything/AFFiNE/blob/e3ffd04804759c309fd8d1f301163c34b11748f1/apps/docs/src/app.tsx#L21-L25

I think it's not a good practice to import `vite` directly. I hope `import.meta.url` can be consistent

**Comment by himself65** [comment]
I try to import 'vite', but 

```
/Users/himself65/.nvm/versions/node/v18.16.0/bin/yarn run dev
Listening on 3000
9:47:10 PM [vite] Error when evaluating SSR module /@fs/Users/himself65/Code/AFFiNE/node_modules/esbuild/lib/main.js:
|- ReferenceError: module is not defined
    at eval (/Users/himself65/Code/AFFiNE/node_modules/esbuild/lib/main.js:48:1)
    at instantiateModule (file:///Users/himself65/Code/AFFiNE/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:15)

Cannot render RSC ReferenceError: module is not defined
    at eval (/Users/himself65/Code/AFFiNE/node_modules/esbuild/lib/main.js:48:1)
    at instantiateModule (file:///Users/himself65/Code/AFFiNE/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:15)
9:47:10 PM [vite] Error when evaluating SSR module /@fs/Users/himself65/Code/AFFiNE/node_modules/vite/dist/node/chunks/dep-e8f070e8.js: failed to import "/@fs/Users/himself65/Code/AFFiNE/node_modules/esbuild/lib/main.js"
|- ReferenceError: module is not defined
    at eval (/Users/himself65/Code/AFFiNE/node_modules/esbuild/lib/main.js:48:1)
    at instantiateModule (file:///Users/himself65/Code/AFFiNE/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:15)

9:47:10 PM [vite] Error when evaluating SSR module /@fs/Users/himself65/Code/AFFiNE/node_modules/vite/dist/node/index.js: failed to import "/@fs/Users/himself65/Code/AFFiNE/node_modules/vite/dist/node/chunks/dep-e8f070e8.js"
|- ReferenceError: module is not defined
    at eval (/Users/himself65/Code/AFFiNE/node_modules/esbuild/lib/main.js:48:1)
    at instantiateModule (file:///Users/himself65/Code/AFFiNE/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:15)

9:47:10 PM [vite] Error when evaluating SSR module /src/app.tsx: failed to import "/@fs/Users/himself65/Code/AFFiNE/node_modules/vite/dist/node/index.js"
|- ReferenceError: module is not defined
    at eval (/Users/himself65/Code/AFFiNE/node_modules/esbuild/lib/main.js:48:1)
    at instantiateModule (file:///Users/himself65/Code/AFFiNE/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:15)
```

**Comment by dai-shi** [comment]
> It might be better to have dev and build paths to be the same level from the root.

I would like to see if this works.

**Comment by dai-shi** [comment]
It kind of works, but I realized it doesn't help anyway for `readFile` case, because we bundle server files too (tbh, I get a little skeptical with this design.)

I'll see if we can do:
```js
import { rootDir } from 'waku/server';

const root = rootDir();
```

And, we can eliminate: https://github.com/dai-shi/waku/blob/62745b77289e53ba72a7e742b5a024672d849672/src/server.ts#L32

**Comment by dai-shi** [comment]
`rootDir` in #87 should help, but not like what you would expect. I think you should basically copy src/input.txt to dist/src/input.txt. (We should probably avoid using `src` folder name.)

**Comment by dai-shi** [comment]
> It might be better to have dev and build paths to be the same level from the root.

I'll try that again.
