### ISSUE TITLE
not compatible with `@vanilla-extract/css`

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#59]
See https://github.com/Himself65/affine-waku/tree/css-issue

**Comment by dai-shi** [comment]
does it emit for client bundle but not for server bundle?

**Comment by Himself65** [comment]
> does it emit for client bundle but not for server bundle?

Both not be emitted, I'm now debugging it.

**Comment by Himself65** [comment]
It's weird when running waku source code. I think it might need some improvement on DX

**Comment by dai-shi** [comment]
Not sure if I follow, but I agree there are tons of room for improvement in terms of Waku's DX.

**Comment by dai-shi** [comment]
> Both not be emitted

That's unfortunate. I hoped it would at least work for client.

**Comment by Himself65** [comment]
Sorry, my mistake. I tried it again

The issue is:
if the css.ts file is only imported by the server component, CSS file won't emit
If it imported by client component, it will

**Comment by Himself65** [comment]
It think generates the wrong output code

```js
import { jsxDEV } from "react/jsx-dev-runtime";
import { Counter } from "./rsc0.js";
import { Suspense } from "react";
import { setFileScope, endFileScope } from "@vanilla-extract/css/fileScope";
import { style } from "@vanilla-extract/css";
setFileScope("src/App.css.ts", "affine-waku");
const container = style(
  { border: "3px red dashed", margin: "1em", padding: "1em" }
);
style(
  { border: "3px blue dashed", margin: "1em", padding: "1em" }
);
endFileScope();
const App = ({ name = "Anonymous" }) => {
  return /* @__PURE__ */ jsxDEV("div", { className: container, children: [
    /* @__PURE__ */ jsxDEV("h1", { children: [
      "Hello ",
      name,
      "!!"
    ] }, void 0, true, {
      fileName: "/Users/himself65/Code/affine-waku/src/App.tsx",
      lineNumber: 8,
      columnNumber: 7
    }, globalThis),
    /* @__PURE__ */ jsxDEV("h3", { children: "This is a server component." }, void 0, false, {
      fileName: "/Users/himself65/Code/affine-waku/src/App.tsx",
      lineNumber: 9,
      columnNumber: 7
    }, globalThis),
    /* @__PURE__ */ jsxDEV(Suspense, { fallback: "loading...", children: /* @__PURE__ */ jsxDEV(Counter, {}, void 0, false, {
      fileName: "/Users/himself65/Code/affine-waku/src/App.tsx",
      lineNumber: 11,
      columnNumber: 9
    }, globalThis) }, void 0, false, {
      fileName: "/Users/himself65/Code/affine-waku/src/App.tsx",
      lineNumber: 10,
      columnNumber: 7
    }, globalThis)
  ] }, void 0, true, {
    fileName: "/Users/himself65/Code/affine-waku/src/App.tsx",
    lineNumber: 7,
    columnNumber: 5
  }, globalThis);
};
export {
  App as default
};
```

**Comment by dai-shi** [comment]
that looks tough...

**Comment by dai-shi** [comment]
#106 includes something related to this.
Can you check what happens with the latest version `v0.14.0`?

**Comment by himself65** [comment]
OK

**Comment by dai-shi** [comment]
@himself65 please check this too. 🙏

**Comment by himself65** [comment]
not working still

see https://github.com/himself65/waku-ecosystem/tree/main/playground/waku-vanilla-extract-css

**Comment by dai-shi** [comment]
That's unfortunate...

**Comment by himself65** [comment]
I get the error

```bash
9:48:01 PM [vite] Error when evaluating SSR module /src/components/App.css.ts:
|- Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
    at Object.getFileScope (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.cjs.dev.js:35:11)
    at generateIdentifier (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:175:49)
    at Proxy.style (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:374:19)
    at eval (/Users/himself65/Code/waku/playground/extract-css/src/components/App.css.ts:5:41)
    at async instantiateModule (file:///Users/himself65/Code/waku/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.2/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)

9:48:01 PM [vite] Error when evaluating SSR module /src/components/App.tsx: failed to import "/src/components/App.css.ts"
|- Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
    at Object.getFileScope (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.cjs.dev.js:35:11)
    at generateIdentifier (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:175:49)
    at Proxy.style (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:374:19)
    at eval (/Users/himself65/Code/waku/playground/extract-css/src/components/App.css.ts:5:41)
    at async instantiateModule (file:///Users/himself65/Code/waku/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.2/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)

Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
    at Object.getFileScope (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.cjs.dev.js:35:11)
    at generateIdentifier (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:175:49)
    at Proxy.style (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:374:19)
    at eval (/Users/himself65/Code/waku/playground/extract-css/src/components/App.css.ts:5:41)
    at async instantiateModule (file:///Users/himself65/Code/waku/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.2/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)
Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
    at Object.getFileScope (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.cjs.dev.js:35:11)
    at generateIdentifier (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:175:49)
    at Proxy.style (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:374:19)
    at eval (/Users/himself65/Code/waku/playground/extract-css/src/components/App.css.ts:5:41)
    at async instantiateModule (file:///Users/himself65/Code/waku/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.2/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9) {
  digest: ''
}
Cannot render HTML Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
    at Object.getFileScope (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.cjs.dev.js:35:11)
    at generateIdentifier (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:175:49)
    at Proxy.style (/Users/himself65/Code/waku/node_modules/.pnpm/@vanilla-extract+css@1.13.0/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:374:19)
    at eval (/Users/himself65/Code/waku/playground/extract-css/src/components/App.css.ts:5:41)
    at async instantiateModule (file:///Users/himself65/Code/waku/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.2/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9) {
  digest: ''
}


```

**Comment by himself65** [comment]
I try in the latest version. It also now cannot run in the client component

**Comment by dai-shi** [comment]
Hoped to support react-tweet #90 too, but it still doesn't.
We need someone to help on it.

**Comment by himself65** [comment]
I guess there might be because of the config plugins missing or something

**Comment by dai-shi** [comment]
For #90, it seems to work for build, but for dev, vite doesn't understand .css in node_modules. There must be something to do with Vite config.

**Comment by Aslemammad** [comment]
I'm putting some time on this and I'll let you know my findings.
