### ISSUE TITLE
[Bug]: cannot start dev server on monorepo

### ISSUE THREAD

**Issue by dinsterizer** [dai-shi/waku#611]
Error on version 0.20.0-beta.2
Working normally on version 0.19.4

The error occurs when creating a waku project inside a turborepo and starting the dev server. The below error occurs when first visiting the dev URL.

```bash
➜  waku-project git:(refactor/migrate-next-to-waku) ✗ pnpm dev

> waku-project@0.0.0 dev /home/dinsterizer/dinui/apps/waku-project
> waku dev

ready: Listening on http://localhost:3000/
Error: Package subpath './router/client.js?v=5a7d017a' is not defined by "exports" in /home/dinsterizer/dinui/node_modules/.pnpm/waku@0.20.0-beta.2_react-dom@18.3.0-canary-56e20051c-20240311_react-server-dom-webpack@18.3.0_bzlbhc2yqsc4fuawbon66r4mu4/node_modules/waku/package.json imported from /home/dinsterizer/dinui/node_modules/.pnpm/waku@0.20.0-beta.2_react-dom@18.3.0-canary-56e20051c-20240311_react-server-dom-webpack@18.3.0_bzlbhc2yqsc4fuawbon66r4mu4/node_modules/waku/dist/lib/renderers/html-renderer.js
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:9)
    at packageResolve (node:internal/modules/esm/resolve:811:14)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/esm/translators:158:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:207:14)
    at Object.get (file:///home/dinsterizer/dinui/node_modules/.pnpm/waku@0.20.0-beta.2_react-dom@18.3.0-canary-56e20051c-20240311_react-server-dom-webpack@18.3.0_bzlbhc2yqsc4fuawbon66r4mu4/node_modules/waku/dist/lib/renderers/html-renderer.js:159:81)
    at resolveClientReference (/home/dinsterizer/dinui/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-56e20051c-20240311_react-dom@18.3.0-canary-56e20051c-2_t5xopm6eahg3wynfxkygyrnqby/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:106:43)
    at resolveModule (/home/dinsterizer/dinui/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-56e20051c-20240311_react-dom@18.3.0-canary-56e20051c-2_t5xopm6eahg3wynfxkygyrnqby/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2059:25)
    at processFullRow (/home/dinsterizer/dinui/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-56e20051c-20240311_react-dom@18.3.0-canary-56e20051c-2_t5xopm6eahg3wynfxkygyrnqby/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2153:9)
    at processBinaryChunk (/home/dinsterizer/dinui/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-56e20051c-20240311_react-dom@18.3.0-canary-56e20051c-2_t5xopm6eahg3wynfxkygyrnqby/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2323:7)
    at progress (/home/dinsterizer/dinui/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-56e20051c-20240311_react-dom@18.3.0-canary-56e20051c-2_t5xopm6eahg3wynfxkygyrnqby/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2410:5) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
Cannot process SSR Error: Package subpath './router/client.js?v=5a7d017a' is not defined by "exports" in /home/dinsterizer/dinui/node_modules/.pnpm/waku@0.20.0-beta.2_react-dom@18.3.0-canary-56e20051c-20240311_react-server-dom-webpack@18.3.0_bzlbhc2yqsc4fuawbon66r4mu4/node_modules/waku/package.json imported from /home/dinsterizer/dinui/node_modules/.pnpm/waku@0.20.0-beta.2_react-dom@18.3.0-canary-56e20051c-20240311_react-server-dom-webpack@18.3.0_bzlbhc2yqsc4fuawbon66r4mu4/node_modules/waku/dist/lib/renderers/html-renderer.js
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:9)
    at packageResolve (node:internal/modules/esm/resolve:811:14)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/esm/translators:158:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:207:14)
    at Object.get (file:///home/dinsterizer/dinui/node_modules/.pnpm/waku@0.20.0-beta.2_react-dom@18.3.0-canary-56e20051c-20240311_react-server-dom-webpack@18.3.0_bzlbhc2yqsc4fuawbon66r4mu4/node_modules/waku/dist/lib/renderers/html-renderer.js:159:81)
    at resolveClientReference (/home/dinsterizer/dinui/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-56e20051c-20240311_react-dom@18.3.0-canary-56e20051c-2_t5xopm6eahg3wynfxkygyrnqby/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:106:43)
    at resolveModule (/home/dinsterizer/dinui/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-56e20051c-20240311_react-dom@18.3.0-canary-56e20051c-2_t5xopm6eahg3wynfxkygyrnqby/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2059:25)
    at processFullRow (/home/dinsterizer/dinui/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-56e20051c-20240311_react-dom@18.3.0-canary-56e20051c-2_t5xopm6eahg3wynfxkygyrnqby/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2153:9)
    at processBinaryChunk (/home/dinsterizer/dinui/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-56e20051c-20240311_react-dom@18.3.0-canary-56e20051c-2_t5xopm6eahg3wynfxkygyrnqby/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2323:7)
    at progress (/home/dinsterizer/dinui/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-56e20051c-20240311_react-dom@18.3.0-canary-56e20051c-2_t5xopm6eahg3wynfxkygyrnqby/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2410:5) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
file:///home/dinsterizer/dinui/node_modules/.pnpm/@hono+node-server@1.8.2/node_modules/@hono/node-server/dist/index.mjs:111
    throw new TypeError("ReadableStream is locked.");
          ^

TypeError: ReadableStream is locked.
    at writeFromReadableStream (file:///home/dinsterizer/dinui/node_modules/.pnpm/@hono+node-server@1.8.2/node_modules/@hono/node-server/dist/index.mjs:111:11)
    at responseViaCache (file:///home/dinsterizer/dinui/node_modules/.pnpm/@hono+node-server@1.8.2/node_modules/@hono/node-server/dist/index.mjs:291:12)
    at responseViaResponseObject (file:///home/dinsterizer/dinui/node_modules/.pnpm/@hono+node-server@1.8.2/node_modules/@hono/node-server/dist/index.mjs:313:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by dai-shi** [comment]
I didn't even know that v0.19.4 worked with monorepo. ref: #429 

Does v0.20.0-beta.2 work in a singe repo?

It might be a regression with #552. @Aslemammad ?

**Comment by jangxyz** [comment]
Same here. It was my first attempt on waku, and reached here.

The error I was seeing with `npm create waku@next` (version @0.8.0-beta.2) was:

```
$ pnpm dev
> waku-PACKAGE@0.0.1 dev /Users/jangxyz/MONOREPO_PATH/packages/waku-PACKAGE
> waku dev

ready: Listening on http://localhost:3000/
Cannot process SSR Error: Error: Unknown variable dynamic import: ../../../../../MONOREPO_PATH/packages/waku-PACKAGE/src/pages/_layout.tsx
    at file:///Users/jangxyz/MONOREPO_PATH/node_modules/.pnpm/waku@0.20.0-beta.2_react-dom@18.3.0-canary-56e20051c-20240311_react-server-dom-webpack@18.3.0_bzlbhc2yqsc4fuawbon66r4mu4/node_modules/waku/dist/lib/renderers/dev-worker-api.js:132:60
    at Worker.<anonymous> (file:///Users/jangxyz/MONOREPO_PATH/node_modules/.pnpm/waku@0.20.0-beta.2_react-dom@18.3.0-canary-56e20051c-20240311_react-server-dom-webpack@18.3.0_bzlbhc2yqsc4fuawbon66r4mu4/node_modules/waku/dist/lib/renderers/dev-worker-api.js:34:52)
    at Worker.emit (node:events:526:35)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

```

Trying out the previous version, as noted above, works.

```bash
npm create waku@0.7.4
```

```
$ pnpm dev

> waku-PACKAGE@0.0.0 dev /Users/jangxyz/MONOREPO_PATH/packages/waku-PACKAGE> waku dev --with-ssr

ready: Listening on http://localhost:3000/
```

**Comment by Aslemammad** [comment]
@dai-shi Do you remember the `.split('?')[0]`? 

That's what it fixed. I don't know why it's not being applied. 

```
Error: Package subpath './router/client.js?v=5a7d017a' is not defined by "exports" in /home/dinsterizer/dinui/node_modules/.pnpm/waku@0.20.0-beta.2_react-dom@18.3.0-canary-56e20051c-20240311_react-server-dom-webpack@18.3.0_bzlbhc2yqsc4fuawbon66r4mu4/node_modules/waku/package.json imported from /home/dinsterizer/dinui/node_modules/.pnpm/waku@0.20.0-beta.2_react-dom@18.3.0-canary-56e20051c-20240311_react-server-dom-webpack@18.3.0_bzlbhc2yqsc4fuawbon66r4mu4/node_modules/waku/dist/lib/renderers/html-renderer.js
```

**Comment by dinsterizer** [comment]
> I didn't even know that v0.19.4 worked with monorepo. ref: #429
> 
> Does v0.20.0-beta.2 work in a singe repo?
> 
> It might be a regression with #552. @Aslemammad ?

I tried 'waku dev' and 'waku build' and can confirm that it works as expected in a single repo. 

Notice: I only test some basic functions and do not go deeper."

**Comment by dai-shi** [comment]
@Aslemammad It's monorepo only (and standalone) which we don't check during development.

@dinsterizer @jangxyz Can you guys help @Aslemammad to create a minimal reproduction?

**Comment by dinsterizer** [comment]
Step 1: `pnpm dlx create-turbo@latest` for creating a new monorepo with turborepo (It includes two Next.js sites, but never mind)
Step 2: cd inside monorepo and `cd apps` -> `pnpm create waku@next` -> cd created waku -> `pnpm install`

So easy @Aslemammad

**Comment by jangxyz** [comment]
Here's minimal reproduction, based om pnpm workspaces: [jangxyz/waku-in-monorepo](https://github.com/jangxyz/waku-in-monorepo)

<details>

<summary>Steps to reproduce:</summary>

```bash
pnpm init
echo 'packages:\n  - packages/*' > pnpm-workspace.yaml

mkdir packages
cd packages

npm create waku@next # accept default options
cd waku-project
pnpm install

pnpm run dev # and access localhost:3000
```

</details>

My original project was stuffed with others projects, and this one turned out to spit out error just like dinsterizer's. Not sure why my original error disappeared, possibly may be interfering with other packages.

**Comment by Aslemammad** [comment]
let me see what can I do

**Comment by Aslemammad** [comment]
#614 will fix it, hopefully.

**Comment by dai-shi** [comment]
@dinsterizer @jangxyz could you guys try it in your environment?

You can install the codesandbox build.
https://ci.codesandbox.io/status/dai-shi/waku/pr/614
Please see "Local Install Instructions" ☝️

**Comment by jangxyz** [comment]
Yup, confirmed it worked. 👍 

<img width="1728" alt="Screenshot 2024-03-24 at 2 05 48 PM" src="https://github.com/dai-shi/waku/assets/52015/be363e08-b999-4e7d-b070-b76c13c7ca63">

* Left side: before PR (`port 3000`)
* Right side: after `#614` (`port 3001`)
