### ISSUE TITLE
[BUG] catch-all-routes failed in build mode

### ISSUE THREAD

**Issue by PerfectPan** [dai-shi/waku#638]
I created [...catchAll].tsx in the pages directory.
It works fine in `waku dev` while error in `waku build`

repo: https://github.com/PerfectPan/waku-issue-638

```
vite v5.2.4 building SSR bundle for production...
✓ 43 modules transformed.
✓ built in 485ms
vite v5.2.4 building SSR bundle for production...
✓ 44 modules transformed.
dist/assets/_layout-DSStnWda.css                  11.81 kB
dist/assets/rsc1-98568e70c.js                      0.15 kB
dist/pages/_...catchAll_.js                        0.40 kB
dist/components/counter.js                         0.48 kB
dist/components/header.js                          0.71 kB
dist/components/footer.js                          0.72 kB
dist/pages/about.js                                1.18 kB
dist/assets/jsx-runtime.react-server-CXpnQugR.js   1.25 kB
dist/pages/index.js                                1.28 kB
dist/waku-server.js                                1.34 kB
dist/pages/_layout.js                              1.38 kB
dist/assets/rsc2-4c28aedd1.js                      1.62 kB
dist/assets/rsc0-323f488e7.js                      2.67 kB
dist/assets/react.react-server-ButLIT0K.js        10.76 kB
dist/entries.js                                   36.11 kB
dist/rsdw-server.js                               43.29 kB
✓ built in 173ms
vite v5.2.4 building SSR bundle for production...
✓ 57 modules transformed.
dist/ssr/index.html                        1.03 kB
dist/ssr/assets/client-DQOYxFJm.js         0.23 kB
dist/ssr/waku-client.js                    0.28 kB
dist/ssr/assets/rsc1-98568e70c.js          0.75 kB
dist/ssr/assets/indexHtml-Xyp13xJw.js      0.99 kB
dist/ssr/assets/jsx-runtime-DGqypVGD.js    1.02 kB
dist/ssr/assets/main-DMvXN4Hl.js           1.09 kB
dist/ssr/assets/rsc2-4c28aedd1.js         10.47 kB
dist/ssr/react.js                         11.85 kB
dist/ssr/rsdw-client.js                   22.36 kB
dist/ssr/assets/rsc0-323f488e7.js         25.77 kB
dist/ssr/rd-server.js                    243.74 kB
dist/ssr/assets/index-tZQmVn07.js        271.16 kB
✓ built in 474ms
vite v5.2.4 building for production...
✓ 40 modules transformed.
dist/public/index.html                        1.05 kB │ gzip:  0.46 kB
dist/public/assets/client-BnvIMyNe.js         0.10 kB │ gzip:  0.11 kB
dist/public/assets/rsc0-323f488e7.js          0.21 kB │ gzip:  0.17 kB
dist/public/assets/rsc1-98568e70c.js          0.42 kB │ gzip:  0.31 kB
dist/public/assets/main-BIUuM6yG.js           0.61 kB │ gzip:  0.37 kB
dist/public/assets/jsx-runtime-B_JgUp2p.js    0.63 kB │ gzip:  0.42 kB
dist/public/assets/indexHtml-dW-kDFoL.js      1.32 kB │ gzip:  0.71 kB
dist/public/assets/rsc2-4c28aedd1.js          5.25 kB │ gzip:  2.13 kB
dist/public/assets/index-DTKtMr2B.js          8.09 kB │ gzip:  3.06 kB
dist/public/assets/client-CxKIwf2S.js       192.42 kB │ gzip: 60.39 kB
✓ built in 290ms
file:///Users/perfectpan/Workspace/waku-demo/waku-project/dist/entries.js:12
    (typeof queueMicrotask === "function" ? queueMicrotask : setTimeout)(reject.bind(null, new Error("Unknown variable dynamic import: " + path)));
                                                                                           ^

Error: Unknown variable dynamic import: ./pages/_...catchAll_.tsx
    at file:///Users/perfectpan/Workspace/waku-demo/waku-project/dist/entries.js:12:92
    at new Promise (<anonymous>)
    at __variableDynamicImportRuntimeHelper (file:///Users/perfectpan/Workspace/waku-demo/waku-project/dist/entries.js:11:10)
    at loader (file:///Users/perfectpan/Workspace/waku-demo/waku-project/dist/entries.js:601:14)
    at file:///Users/perfectpan/Workspace/waku-demo/waku-project/dist/entries.js:570:25
    at async configure (file:///Users/perfectpan/Workspace/waku-demo/waku-project/dist/entries.js:423:7)
    at async async.unstable_setShouldSkip.unstable_setShouldSkip (file:///Users/perfectpan/Workspace/waku-demo/waku-project/dist/entries.js:429:5)
    at async getMyPathConfig (file:///Users/perfectpan/Workspace/waku-demo/waku-project/dist/entries.js:139:37)
    at async getBuildConfig (file:///Users/perfectpan/Workspace/waku-demo/waku-project/dist/entries.js:223:24)
    at async getBuildConfig (file:///Users/perfectpan/Workspace/waku-demo/waku-project/node_modules/.pnpm/waku@0.20.0_react-dom@18.3.0-canary-670811593-20240322_react-server-dom-webpack@18.3.0-canary_3kk2h6dtjy7uxdmdy7t4y73ynu/node_modules/waku/dist/lib/renderers/rsc-renderer.js:161:20)

Node.js v20.11.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by dai-shi** [comment]
Thanks for reporting. I think I overlooked that case. Will fix it right away.

**Comment by dai-shi** [comment]
Can you try #640?
https://ci.codesandbox.io/status/dai-shi/waku/pr/640
Find "Local Install Instructions" ☝️

**Comment by PerfectPan** [comment]
It looks fine to me, thx for your timely response to the issue.
