### ISSUE TITLE
Trying to upgrade and getting errors

### ISSUE THREAD

**Issue by hipstersmoothie** [dai-shi/waku#766]
I'm trying to upgrade to the latest beta and I get this error when starting my app

```
TypeError: Cannot assign to read only property 'page' of object '#<Object>'
    at /Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2334:23
    at wakeChunk (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:1992:5)
    at initializeModelChunk (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2186:9)
    at resolveModelChunk (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2129:5)
    at resolveModel (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2716:5)
    at processFullRow (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:3338:9)
    at processBinaryChunk (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:3471:7)
    at progress (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:3558:5)
Cannot process SSR TypeError: Cannot assign to read only property 'page' of object '#<Object>'
    at /Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2334:23
    at wakeChunk (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:1992:5)
    at initializeModelChunk (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2186:9)
    at resolveModelChunk (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2129:5)
    at resolveModel (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2716:5)
    at processFullRow (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:3338:9)
    at processBinaryChunk (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:3471:7)
    at progress (/Users/andrewlisowski/Documents/fwoosh-3/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc.0_react-dom@19.0.0-rc.0_react@19.0.0-rc.0__react@19.0.0-rc_p6bqj3dy2a2jctw2w7d4lhay7m/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:3558:5)
```

Should I report this upstream? This all works on the non-beta version

My repo is [here](https://github.com/fwoosh-dev/fwoosh-3).  The upgrade work is on the `upgrade-waku` branch.

Set up steps:

```
pnpm I
pnpm turbo run build
cd examples/react
pnpm fwoosh dev
```

Navigate to `localhost:3000/bench`

**Comment by dai-shi** [comment]
The build step `pnpm turbo run build` failed for me (a different pnpm version?), but I found you have two react-server-dom-webpack packages.

```
   "react-server-dom-webpack": "19.0.0-beta-e7d213dfb0-20240507",
   "react-server-dom-webpack": "19.0.0-rc.0",
```

Can you make sure to use `rc.0` for everything?

I'm not sure if it relates to the error though. The monorepo setup seems tough.

**Comment by hipstersmoothie** [comment]
I think the real problem is the errors can be really hard to tie to something that caused the error

**Comment by hipstersmoothie** [comment]
In all cases the bug is complaining about a prop. In the case of the table cell it doesn't like `node`

**Comment by hipstersmoothie** [comment]
Okay that prop was getting passed to the dom, and that seems to break something

**Comment by dai-shi** [comment]
> So it seems like in this case it's having trouble rendering the client component

interesting as recent changes are basically for the server.
yeah, it's pretty hard to debug.

**Comment by hipstersmoothie** [comment]
All errors seem to be when passing objects to client components

**Comment by dai-shi** [comment]
> All errors seem to be when passing objects to client components

from server components? So, is it easy to create a very small reproduction?

**Comment by dai-shi** [comment]
> this is probably a problem upstream.

oh, okay.

> I have been getting into situations where I get not found and no output at all though. refreshing once or twice fixes it

Yeah, i've also seen it before. Not sure how it causes it yet.

**Comment by hipstersmoothie** [comment]
I can try to pare it down

**Comment by hipstersmoothie** [comment]
Okay got it down to just 1 file. hopefully I didn't miss any setup steps

[Here is the repo](https://github.com/hipstersmoothie/waku-repro)

Setup should be

```
pnpm I
cd packages/fwoosh
pnpm waku dev
```

Then navigate to `http://localhost:3000/iframe/test`

![CleanShot 2024-06-30 at 22 58 39@2x](https://github.com/dai-shi/waku/assets/1192452/f39efbfd-f49d-4ea0-9436-607f39384b65)

When I remove the context it seems to work (but I want the context 😅 )

**Comment by dai-shi** [comment]
I was hoping to run it on StackBlitz:
https://stackblitz.com/github/hipstersmoothie/waku-repro/tree/main/packages/fwoosh

But, it can't install deps in the subfolder. 😅

**Comment by dai-shi** [comment]
Hm, I can reproduce the error locally.

> When I remove the context it seems to work (but I want the context 😅 )

But, it sounds like we could make a smaller repro, even without monorepo.

We have an e2e test with `e2e/fixtures/ssr-context-provider`. I wonder how it's different.

**Comment by hipstersmoothie** [comment]
i've simplified it further too

I'll remove all the monorepo stuff if that helps

**Comment by hipstersmoothie** [comment]
monorepo stuff removed

**Comment by hipstersmoothie** [comment]
Okay simplified it as much as I think I can. It seems to have to do with the re-use of `page` and `story`. If I move the empty object to the args it works.

**Comment by hipstersmoothie** [comment]
doing this also works

![CleanShot 2024-06-30 at 23 26 29@2x](https://github.com/dai-shi/waku/assets/1192452/40b3125b-6ea6-4380-83b5-c4ee655336e7)

**Comment by dai-shi** [comment]
> Okay simplified it as much as I think I can.

This is great!!! But, I wish more if it can fit in e2e fixture.
`src/pages/_layout.tsx` isn't necessary.
I think it can be just one page `src/pages/index.tsx`.
I wonder if `src/Button.stories.tsx` is required for the reproduction.
Do we need both Decorator.tsx files?

**Comment by dai-shi** [comment]
Hmm, one decorator is a server component and the other is a client component.

**Comment by hipstersmoothie** [comment]
Yeah the decorators are needed and the way I compose them is too

**Comment by dai-shi** [comment]
I think it can be as simple as:
```jsx
<PageContextProvider value={page}>
  <ClientHolder page={page}>
    <ServerHolder page={page}>
      <ClientButton />
    </ServerHolder>
  </ClientHolder>
</PageContextProvider>
```
Or something like that. (Well "simple" might be subjective)

**Comment by hipstersmoothie** [comment]
i'm finding I can only repro if the loop is there

**Comment by dai-shi** [comment]
So, it looks like when we pass `page` object to a client component, the `page` object got frozen (?) and the error occurs.

**Comment by dai-shi** [comment]
> i'm finding I can only repro if the loop is there

Oh, really. That's interesting.

**Comment by hipstersmoothie** [comment]
I was wrong. what's important is the order of the decorators

CenteredDecorator > A11yDecorator (doesn't work)
A11yDecorator > CenteredDecorator (works)

**Comment by hipstersmoothie** [comment]
example is just this now

```tsx
import { StoryContextProvider } from "../../components/Context";
import A11yDecorator from "../../A11yDecorator";
import CenteredDecorator from "../../CenteredDecorator";

export default function Iframe() {
  const page = {};

  return (
    <StoryContextProvider value={{ page }}>
      <CenteredDecorator page={page}>
        <A11yDecorator page={page}>
          <div>foo</div>
        </A11yDecorator>
      </CenteredDecorator>
    </StoryContextProvider>
  );
}
```

**Comment by dai-shi** [comment]
Nice! We could further reduce files and lines, but it's pretty understandable now. Thanks.

So, I did this change:
```diff
diff --git a/package.json b/package.json
index 8ad6a33..763059d 100644
--- a/package.json
+++ b/package.json
@@ -3,9 +3,9 @@
   "version": "0.1.0",
   "private": true,
   "dependencies": {
-    "react": "19.0.0-rc.0",
-    "react-dom": "19.0.0-rc.0",
-    "react-server-dom-webpack": "19.0.0-rc.0",
+    "react": "19.0.0-beta-e7d213dfb0-20240507",
+    "react-dom": "19.0.0-beta-e7d213dfb0-20240507",
+    "react-server-dom-webpack": "19.0.0-beta-e7d213dfb0-20240507",
     "waku": "^0.21.0-beta.0"
   },
   "devDependencies": {
```

And, it works. So, it looks like an upstream issue. You want to find the exact PR in React repo that causes this error and see if it's intentional.
